### ISSUE TITLE
merge muxado2/wip ? spec?

### ISSUE THREAD

**Issue by jbenet** [inconshreveable/muxado#11]
Hey @inconshreveable may want to merge muxado2/wip? Also, may be nice to have a spec for interoperable impls in other languages? even if just an example based listing of frames

And a more general thought: _ideally_, _it could be_ http2-compliant so other languages could use http2 based muxers to talk to muxado, but not sure how much muxado departs from the spdy framing. maybe that ship's sailed and docked elsewhere by now.

**Comment by inconshreveable** [comment]
Yeah, I've been putting it off just because I've been afraid of 'finalizing' a public API, but I think the right thing to do is just take one more pass at it and says to everyone, "pin your dependency if you don't want to break". It's very unfortunate there's no official tool-supported way to deal with this problem for library authors.

The ship has sailed on the http2 compat, but there should definitely be a spec for this, I agree.

I'm going to try to take another pass at my open source projects in the next week or so after I finish up some business-critical work first.

**Comment by jbenet** [comment]
thanks @inconshreveable ! and no rush :)

**Comment by nickwondra** [comment]
+1 for merging `wip` into `master`. I just came across this project as I was trying to build something very similar, and I'm very happy I don't have to roll my own version of muxado! The fixes in the `wip` branch will be critical for my application, especially the improvements for reduced memory usage.

Thanks for building and continuing to support this project @inconshreveable!

**Comment by ginkoob** [comment]
+1

**Comment by inconshreveable** [comment]
merged wip into master. should have done this a long time ago. when i get a spare weekend I'll try to get some docs up about the policy but it's basically going to be what the go community has adopted:

- If you want any API stability, vendor.
- Any API changes will be documented
